use std::collections::{hash_map::RandomState, BTreeSet};
use std::fmt::Write;
use std::hash::{BuildHasher, Hasher};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;
use std::time::{SystemTime, UNIX_EPOCH};

/// Sampling families behind the one stream type the tool uses.
///
/// Every layout decision used to ride a single xorshift64* stream, which meant
/// one recovered draw sequence was one step from rolling the others: same mixer,
/// same state, same period. Each domain still owns its own seed-tagged stream,
/// and now the domains also own different *mixing families*, so no single
/// recurrence explains names, validator shape and transport layout at once:
///
/// * [`Family::Xs`] - xorshift64*: output shape (identifier pools, name
///   shortening, method/key maps).
/// * [`Family::Lcg`] - a 64-bit linear congruential generator with Hull-Dobell
///   full-period constants and a bijective output finalizer: structure (the
///   validator's search tree, the lane route, register/operand lowering, the
///   per-handler routine arms).
/// * [`Family::Sfc`] - an sfc64-style four-word mixing state: transport and
///   noise (alphabets, segment order, key material, spelling pools).
///
/// A family is a *sampling* choice only: nothing here is presented as a cipher,
/// and no generated byte depends on anything but (seed, family, call order).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Family {
    Xs,
    Lcg,
    Sfc,
}

/// Multiplier and increment of [`Family::Lcg`]. They stay `pub(crate)` so the
/// gate can verify the Hull-Dobell conditions on the constants the generator
/// actually uses instead of on restated copies: with m = 2^64 the conditions are
/// "increment is odd" and "multiplier - 1 is a multiple of every prime factor of
/// m, and of 4 because 4 divides m". Since 2 is the only prime factor of 2^64,
/// those two facts give a period of exactly 2^64 from every start state.
pub(crate) const LCG_MULT: u64 = 0x0000_0369_3ea1_f41d;
pub(crate) const LCG_INCR: u64 = 0x1405_7b7e_f767_814f;

/// Small deterministic generator for layout and identifier randomization.
///
/// This is deliberately not presented as a cryptographic primitive. Data
/// encryption and key derivation belong to a later milestone.
pub(crate) struct Prng {
    family: Family,
    state: u64,
    /// Mixing words, used only by [`Family::Sfc`].
    aux: [u64; 3],
}

/// Bounded draw with no division and no remainder: one 128-bit product of the
/// sample and the bound, keeping the high half (multiply-shift). The bucket
/// decision rides the top bits of the sample, so a family's structurally weak
/// low bits - an LCG's bit 0 alternates, `x * odd` keeps a xorshift's bit 0 at
/// period 2 - never pick a bucket, and every bucket's preimage differs by at
/// most one value. `raw % upper` instead hands its whole surplus to the first
/// `2^64 mod upper` buckets, which is exactly the kind of predictable structure
/// an analyst looks for when guessing how many arms a table has.
pub(crate) fn scale(raw: u64, upper: usize) -> usize {
    if upper <= 1 {
        0
    } else {
        (((raw as u128) * (upper as u128)) >> 64) as usize
    }
}

impl Prng {
    pub fn new(seed: u64) -> Self {
        Self::with_family(Family::Xs, seed)
    }

    /// Full-period LCG stream, see [`Family::Lcg`] and [`LCG_MULT`]/[`LCG_INCR`].
    pub fn lcg(seed: u64) -> Self {
        Self::with_family(Family::Lcg, seed)
    }

    /// sfc64-style stream, see [`Family::Sfc`].
    pub fn sfc(seed: u64) -> Self {
        Self::with_family(Family::Sfc, seed)
    }

    /// Which mixer this stream uses. Test-only: no generated byte depends on
    /// it, but the family-split gates below read it.
    #[cfg(test)]
    pub fn family(&self) -> Family {
        self.family
    }

    fn with_family(family: Family, seed: u64) -> Self {
        let state = if seed == 0 {
            0x9e37_79b9_7f4a_7c15
        } else {
            seed
        };
        let mut random = Self {
            family,
            state,
            aux: [0; 3],
        };
        if family == Family::Sfc {
            // The four mixing words come from one seed via splitmix64, then the
            // mixer is warmed up so a caller never sees the seeding arithmetic.
            let mut source = state;
            let mut words = [0u64; 4];
            for word in words.iter_mut() {
                source = source.wrapping_add(0x9e37_79b9_7f4a_7c15);
                let mut value = source;
                value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
                value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
                *word = value ^ (value >> 31);
            }
            random.state = words[0];
            random.aux = [words[1], words[2], words[3]];
            // An all-zero mixing state would be a fixed point; the seeding cannot
            // produce one, and this keeps that true for any future seeder.
            if random.state | random.aux[0] | random.aux[1] | random.aux[2] == 0 {
                random.state = 0x9e37_79b9_7f4a_7c15;
            }
            for _ in 0..12 {
                random.next_u64();
            }
        }
        random
    }

    pub fn next_u64(&mut self) -> u64 {
        match self.family {
            Family::Xs => {
                let mut value = self.state;
                value ^= value >> 12;
                value ^= value << 25;
                value ^= value >> 27;
                self.state = value;
                value.wrapping_mul(0x2545_f491_4f6c_dd1d)
            }
            Family::Lcg => {
                // One full-period state step, then a bijective finalizer. The
                // finalizer cannot shorten the state period (it is a permutation
                // of the state) and it removes the LCG's low-bit regularity from
                // every consumer, including any that reads bit 0 directly.
                self.state = self.state.wrapping_mul(LCG_MULT).wrapping_add(LCG_INCR);
                let mut value = self.state;
                value = (value ^ (value >> 33)).wrapping_mul(0xff51_afd7_ed55_8ccd);
                value = (value ^ (value >> 33)).wrapping_mul(0xc4a9_fdd1_9460_9c73);
                value ^ (value >> 33)
            }
            Family::Sfc => {
                // Four words: two shift/xor mixing words, one additive mixing word
                // and a counter folded into the output. Carries make the output
                // depend on all three mixing words at once.
                let result = self
                    .state
                    .wrapping_add(self.aux[0])
                    .wrapping_add(self.aux[2]);
                self.aux[2] = self.aux[2].wrapping_add(1).wrapping_add(result);
                let mixed = self.state ^ self.aux[0];
                self.state = self.aux[0].wrapping_add(self.aux[0] << 5);
                self.aux[0] = (self.aux[1] >> 3) ^ mixed;
                self.aux[1] = mixed.wrapping_add(result);
                result
            }
        }
    }

    /// One unbiased coin. Rides the top bit of the draw for the same reason
    /// [`scale`] does.
    pub fn coin(&mut self) -> bool {
        (self.next_u64() >> 63) != 0
    }

    pub fn index(&mut self, upper: usize) -> usize {
        scale(self.next_u64(), upper)
    }

    pub fn shuffle<T>(&mut self, values: &mut [T]) {
        for index in (1..values.len()).rev() {
            let other = self.index(index + 1);
            values.swap(index, other);
        }
    }

    pub fn unique_opcodes(&mut self, count: usize) -> Vec<u16> {
        let mut used = BTreeSet::new();
        let mut result = Vec::with_capacity(count);
        while result.len() < count {
            // 257..=65256, drawn through the same bias-free bounded sampler as
            // every other choice in the tool.
            let candidate = 257 + self.index(65_000) as u16;
            if used.insert(candidate) {
                result.push(candidate);
            }
        }
        result
    }

    /// Spell an exact non-negative integer using only forms accepted by the
    /// selected output target. Lua 5.1 receives decimal/hexadecimal forms;
    /// Luau may additionally receive binary digits and separators.
    pub fn integer_literal(&mut self, value: u64, luau: bool) -> String {
        match self.index(if luau { 3 } else { 2 }) {
            0 => value.to_string(),
            1 => format!("0x{value:x}"),
            2 => {
                let digits = format!("{value:b}");
                let first = {
                    let remainder = digits.len() % 4;
                    if remainder == 0 {
                        4
                    } else {
                        remainder
                    }
                };
                let mut result = String::from("0b");
                result.push_str(&digits[..first]);
                for chunk in digits.as_bytes()[first..].chunks(4) {
                    result.push('_');
                    result.push_str(std::str::from_utf8(chunk).expect("binary digits are UTF-8"));
                }
                result
            }
            _ => unreachable!(),
        }
    }

    /// Emit one of several side-effect-free dispatcher comparisons. Only the
    /// opcode comparison changes; handler evaluation order stays unchanged.
    pub fn dispatch_condition(&mut self, opcode: u16, luau: bool) -> String {
        self.dispatch_condition_for("o", opcode, luau)
    }

    /// Variable-parameterized form used by the semantic recipe dispatcher.
    /// The caller supplies an internal identifier, never user source.
    pub fn dispatch_condition_for(&mut self, variable: &str, opcode: u16, luau: bool) -> String {
        debug_assert!(variable
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_'));
        let literal = self.integer_literal(u64::from(opcode), luau);
        let mut result = String::new();
        match self.index(4) {
            0 => write!(result, "{variable}=={literal}").unwrap(),
            1 => write!(result, "{literal}=={variable}").unwrap(),
            2 => write!(result, "not({variable}~={literal})").unwrap(),
            3 => write!(result, "{variable}-{literal}==0").unwrap(),
            _ => unreachable!(),
        }
        result
    }

    /// Spell a "this field must match that value" guard's *reject condition* in
    /// one of several exactly equivalent forms: every result is true exactly when
    /// the two sides differ, which is what the emitted `if <it> then E()end` uses.
    ///
    /// The validator wrote every header, watermark and known-answer rejection as
    /// `left ~= right`, which turned the whole load-time check block into a single
    /// grep anchor: one search found every guard and its pass/fail polarity. The
    /// forms below differ in shape only - same predicate, same short-circuit
    /// structure, same fail-closed behaviour - and which one a site gets is a
    /// per-seed choice like every other spelling in the tool.
    ///
    /// Each form evaluates both sides exactly once. The two-sided order test is
    /// offered only when `pure` says neither side can have an effect, because the
    /// header reads (`b8()`, `b32()`, the segment cursors) advance a read position:
    /// reading one byte twice would shift every field behind it and turn a
    /// validator into a corrupter.
    pub fn reject_unequal(&mut self, left: &str, right: &str, pure: bool) -> String {
        // Both sides must be atomic for the difference forms to stay exact under
        // Lua's left-associative `+`/`-`: a caller that needs a compound operand
        // parenthesizes it. Commas are allowed only inside the parentheses of a
        // call, which is a single evaluation.
        for side in [left, right] {
            debug_assert!(side
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || b"_.#(),".contains(&byte)));
        }
        let text = match self.index(if pure { 5 } else { 4 }) {
            0 => format!("{left}~={right}"),
            1 => format!("not({left}=={right})"),
            2 => format!("{left}-{right}~=0"),
            3 => format!("{right}-{left}~=0"),
            _ => format!("{left}<{right} or {right}<{left}"),
        };
        text
    }

    /// Side-effect-free boundary test for the validator's binary search tree:
    /// `variable < bound` (below) or its exact complement `variable >= bound`.
    /// Each rides in one of several spellings and every bound is byte-sized, so
    /// all forms stay exact on both targets (no double rounding is involved).
    pub fn boundary_condition(
        &mut self,
        variable: &str,
        bound: u16,
        below: bool,
        luau: bool,
    ) -> String {
        debug_assert!(variable
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_'));
        let literal = self.integer_literal(u64::from(bound), luau);
        let mut result = String::new();
        if below {
            match self.index(5) {
                0 => write!(result, "{variable}<{literal}"),
                1 => write!(result, "{literal}>{variable}"),
                2 => write!(result, "not({variable}>={literal})"),
                3 => write!(result, "{variable}-{literal}<0"),
                _ => write!(result, "{literal}-{variable}>0"),
            }
        } else {
            match self.index(4) {
                0 => write!(result, "{variable}>={literal}"),
                1 => write!(result, "{literal}<={variable}"),
                2 => write!(result, "not({variable}<{literal})"),
                _ => write!(result, "{variable}-{literal}>=0"),
            }
        }
        .unwrap();
        result
    }
}

/// Fresh per-generation default, not a cryptographic key. A process-random
/// std hasher initializes the stream once; a bijective mixer of the atomic
/// counter avoids repeats within a process (until the u64 counter wraps).
/// Explicit user seeds never pass through this nondeterministic path.
pub(crate) fn fresh_seed() -> u64 {
    static BASE: OnceLock<u64> = OnceLock::new();
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let base = *BASE.get_or_init(|| {
        let mut hasher = RandomState::new().build_hasher();
        hasher.write_u32(std::process::id());
        hasher.write(
            &SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
                .to_le_bytes(),
        );
        hasher.finish()
    });
    let mut value = base.wrapping_add(COUNTER.fetch_add(1, Ordering::Relaxed));
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}

#[cfg(test)]
mod tests {
    use super::{fresh_seed, scale, Family, Prng, LCG_INCR, LCG_MULT};

    #[test]
    fn default_seeds_are_distinct_across_threads() {
        let threads: Vec<_> = (0..8)
            .map(|_| std::thread::spawn(|| (0..128).map(|_| fresh_seed()).collect::<Vec<_>>()))
            .collect();
        let seeds: std::collections::BTreeSet<_> = threads
            .into_iter()
            .flat_map(|thread| thread.join().unwrap())
            .collect();
        assert_eq!(seeds.len(), 1024);
    }

    /// Which of the nine `boundary_condition` spellings a text uses. Kept as a
    /// separate classifier so the coverage assertion cannot be satisfied by a
    /// collapsed subset.
    fn boundary_label(text: &str) -> &'static str {
        let trimmed = text.trim();
        if let Some(inner) = trimmed
            .strip_prefix("not(")
            .and_then(|body| body.strip_suffix(')'))
        {
            return if inner.contains(">=") {
                "not>="
            } else {
                "not<"
            };
        }
        if let Some(rest) = trimmed.strip_prefix("o-") {
            return if rest.ends_with("<0") {
                "o-K<0"
            } else {
                "o-K>=0"
            };
        }
        if trimmed.starts_with("o<") {
            "o<"
        } else if trimmed.starts_with("o>=") {
            "o>="
        } else if trimmed.ends_with(">o") {
            "K>o"
        } else if trimmed.ends_with("<=o") {
            "K<=o"
        } else if trimmed.ends_with(">0") {
            "K-o>0"
        } else {
            panic!("unexpected boundary spelling {trimmed:?}")
        }
    }

    /// `boundary_condition` is what the validator's search tree partitions on,
    /// so every spelling it can emit must be an exact `<` / `>=` complement over
    /// the whole byte range: one wrong spelling would route records to the wrong
    /// arm (or past every arm) while still looking like a plain dispatch chain.
    /// The parser below accepts exactly the nine forms the renderer can produce
    /// and panics on anything else, so new spellings cannot go uncovered.
    #[test]
    fn boundary_conditions_partition_the_byte_range_exactly() {
        fn literal(token: &str) -> i64 {
            if let Some(hex) = token.strip_prefix("0x") {
                i64::from_str_radix(hex, 16).expect("hex literal")
            } else if let Some(bits) = token.strip_prefix("0b") {
                i64::from_str_radix(&bits.replace('_', ""), 2).expect("binary literal")
            } else {
                token.parse::<i64>().expect("decimal literal")
            }
        }
        fn side(token: &str, value: i64) -> i64 {
            let token = token.trim();
            if token == "o" {
                return value;
            }
            if let Some(rest) = token.strip_prefix("o-") {
                return value - literal(rest.trim());
            }
            if let Some(pos) = token.find("-o") {
                return literal(&token[..pos]) - value;
            }
            literal(token)
        }
        fn holds(text: &str, value: i64) -> bool {
            let trimmed = text.trim();
            if let Some(inner) = trimmed
                .strip_prefix("not(")
                .and_then(|body| body.strip_suffix(')'))
            {
                return !holds(inner, value);
            }
            // `<` and `>` are checked after their inclusive siblings so a
            // leading `<=` is never split into `<` plus a stray `=`.
            for op in ["<=", ">=", "<", ">"] {
                if let Some((left, right)) = trimmed.split_once(op) {
                    let (a, b) = (side(left, value), side(right, value));
                    return match op {
                        "<=" => a <= b,
                        ">=" => a >= b,
                        "<" => a < b,
                        _ => a > b,
                    };
                }
            }
            panic!("unparsable boundary condition {trimmed:?}");
        }

        for luau in [false, true] {
            let mut rng = Prng::new(0xb01d_2024);
            let mut seen = std::collections::BTreeSet::new();
            for bound in 0..=255u16 {
                for below in [true, false] {
                    let text = rng.boundary_condition("o", bound, below, luau);
                    // The bound in the text must be the requested one, and the
                    // two families must be exact complements at every value.
                    for value in [0i64, 1, 63, 64, 127, 128, 254, 255, 256] {
                        let below_holds = holds(&text, value)
                            == (if below {
                                value < i64::from(bound)
                            } else {
                                value >= i64::from(bound)
                            });
                        assert!(below_holds, "{text} at o={value} against {bound}");
                    }
                    seen.insert(boundary_label(&text));
                }
            }
            // Every spelling the renderer owns must actually show up, otherwise
            // the partition check above quietly covers a subset.
            assert_eq!(
                seen.len(),
                9,
                "{target} boundary spellings: {seen:?}",
                target = if luau { "luau" } else { "lua51" }
            );
        }
    }

    #[test]
    fn deterministic_and_unique() {
        let left = Prng::new(42).unique_opcodes(128);
        let right = Prng::new(42).unique_opcodes(128);
        assert_eq!(left, right);
        let mut sorted = left.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 128);
    }

    #[test]
    fn numeric_spelling_is_target_aware() {
        let mut lua = Prng::new(7);
        for _ in 0..64 {
            let literal = lua.integer_literal(0x1234, false);
            assert!(!literal.starts_with("0b"));
            assert!(!literal.contains('_'));
        }

        let mut luau = Prng::new(7);
        let literals: Vec<_> = (0..64)
            .map(|_| luau.integer_literal(0x1234, true))
            .collect();
        assert!(literals.iter().any(|literal| literal.starts_with("0b")));
        assert!(literals.iter().any(|literal| literal.contains('_')));

        let mut dispatch = Prng::new(19);
        for opcode in 1..=64 {
            let condition = dispatch.dispatch_condition_for("rid", opcode, true);
            assert!(condition.contains("rid"));
            let without_keywords = condition.replace("not", "").replace("rid", "");
            assert!(!without_keywords.contains('o'));
        }
    }

    #[test]
    fn lcg_meets_hull_dobell_and_walks_the_whole_reduced_state_space() {
        // Hull-Dobell for m = 2^64, read off the constants the generator uses:
        // the increment is odd, and multiplier - 1 is a multiple of 2 (the only
        // prime factor of m) and of 4 (because 4 divides m). Together these say
        // the state sequence has full period 2^64 from every start state.
        assert_eq!(LCG_INCR % 2, 1, "increment must be coprime with 2^64");
        assert_eq!(
            (LCG_MULT - 1) % 2,
            0,
            "multiplier - 1 must hit every prime factor of m"
        );
        assert_eq!(
            (LCG_MULT - 1) % 4,
            0,
            "m is a multiple of 4, so this is required too"
        );

        // The 2^64 walk itself cannot be run, so the same three conditions are
        // re-checked on a truncated modulus where the full cycle is enumerable:
        // a period-1 state cycle would show up here immediately.
        const M: u64 = 1 << 20;
        let mult = LCG_MULT % M;
        let incr = LCG_INCR % M;
        assert_eq!(incr % 2, 1);
        assert_eq!((mult - 1) % 4, 0);
        let mut seen = vec![false; M as usize];
        let mut state = 0x1234_5678_u64 % M;
        let start = state;
        for step in 0..M {
            state = (state.wrapping_mul(mult).wrapping_add(incr)) % M;
            assert!(!seen[state as usize], "state repeated after {step} steps");
            seen[state as usize] = true;
        }
        assert_eq!(state, start, "the reduced cycle must close exactly at m");
    }

    #[test]
    fn bounded_draw_reads_high_bits_and_spreads_preimages_evenly() {
        // Top-bit semantics: bucket 1 of two starts exactly at 2^63, whereas a
        // remainder mapping would decide this sample from its low bits instead.
        assert_eq!(scale(1 << 63, 2), 1);
        assert_eq!(scale((1 << 63) - 1, 2), 0);
        assert_ne!(
            scale(1 << 63, 3),
            ((1_u128 << 63) % 3) as usize,
            "a remainder draw and a multiply-shift draw must not agree here"
        );
        for bound in 1..=4096usize {
            assert_eq!(scale(0, bound), 0, "zero maps into the first bucket");
            assert_eq!(scale(u64::MAX, bound), bound - 1, "the draw is onto");
            // Preimage sizes differ by at most one value: bucket i spans
            // [ceil(i * 2^64 / bound), ceil((i + 1) * 2^64 / bound)).
            // Bucket 0 is skipped: its lower boundary is zero, so there is
            // no value below it to attribute to a previous bucket.
            for bucket in 1..bound.min(8) {
                let span = 1_u128 << 64;
                let low = (span * bucket as u128 + bound as u128 - 1) / bound as u128;
                assert_eq!(
                    scale(low as u64, bound),
                    bucket,
                    "lower boundary of {bucket}"
                );
                assert_eq!(
                    scale(low as u64 - 1, bound),
                    bucket - 1,
                    "the value below a boundary belongs to the previous bucket"
                );
            }
        }
    }

    #[test]
    fn every_family_balances_the_bits_a_consumer_might_read() {
        // Fixed seeds, so the tolerated spread is not a flaky statistical claim:
        // it just has to prove the finalizers actually shuffle carries upward and
        // that no family leaves a bucket empty (an LCG without a finalizer sets
        // bit 0 to a strict alternation, which shows up here as 50/50 per bit but
        // a 64-bucket histogram of the raw state would not be flat).
        for seed in [1u64, 7001, 4242, u64::MAX] {
            for mut random in [Prng::new(seed), Prng::lcg(seed), Prng::sfc(seed)] {
                let mut counts = [0u32; 64];
                for _ in 0..65_536 {
                    // 65,536 draws over 64 buckets expect 1,024 each; +-15% is
                    // far outside what a broken finalizer would produce.
                    counts[(random.next_u64() & 63) as usize] += 1;
                }
                assert!(
                    counts.iter().all(|&count| (870..=1180).contains(&count)),
                    "{seed} {:?} low-6-bit histogram {counts:?}",
                    random.family()
                );
            }
        }

        // Why the finalizer exists: the raw state walk of the same constants has
        // bit 0 in exact alternation, so a consumer reading the state directly
        // would see a period-2 signal in its own low bit.
        let mut state = 7u64;
        for step in 0..64 {
            state = state.wrapping_mul(LCG_MULT).wrapping_add(LCG_INCR);
            assert_eq!(
                state & 1,
                step % 2,
                "the un-finalized LCG state is expected to alternate in bit 0"
            );
        }
    }

    #[test]
    fn families_are_independent_streams_per_seed() {
        // The constructors really do select different mixers, not just different
        // starting states of one mixer.
        assert_eq!(Prng::new(1).family(), Family::Xs);
        assert_eq!(Prng::lcg(1).family(), Family::Lcg);
        assert_eq!(Prng::sfc(1).family(), Family::Sfc);
        for seed in [0u64, 1, 4095, 7001, 7351, 65535, u64::MAX] {
            let xs: Vec<_> = (0..32)
                .scan(Prng::new(seed), |r, _| Some(r.next_u64()))
                .collect();
            let lcg: Vec<_> = (0..32)
                .scan(Prng::lcg(seed), |r, _| Some(r.next_u64()))
                .collect();
            let sfc: Vec<_> = (0..32)
                .scan(Prng::sfc(seed), |r, _| Some(r.next_u64()))
                .collect();
            assert!(
                xs.iter().zip(lcg.iter()).all(|(a, b)| a != b),
                "{seed}: xs == lcg"
            );
            assert!(
                xs.iter().zip(sfc.iter()).all(|(a, b)| a != b),
                "{seed}: xs == sfc"
            );
            assert!(
                lcg.iter().zip(sfc.iter()).all(|(a, b)| a != b),
                "{seed}: lcg == sfc"
            );
            // Each family must be a function of its seed, not of anything else.
            assert_eq!(
                lcg,
                (0..32)
                    .scan(Prng::lcg(seed), |r, _| Some(r.next_u64()))
                    .collect::<Vec<_>>()
            );
            assert_ne!(
                lcg,
                (0..32)
                    .scan(Prng::lcg(seed ^ 1), |r, _| Some(r.next_u64()))
                    .collect::<Vec<_>>()
            );
        }
    }

    #[test]
    fn routed_domains_never_share_the_shape_stream() {
        // Structural guard for the split: the transport/crypto and structure
        // modules must not sample from the default (output-shape) family again,
        // and the per-handler structure domains must not fall back to xorshift.
        // Read from source, because the family is chosen per construction site.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut routed: std::collections::BTreeMap<String, (usize, usize, usize)> =
            std::collections::BTreeMap::new();
        let mut stack = vec![root.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).expect("source tree") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    stack.push(path);
                    continue;
                }
                if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                    continue;
                }
                let relative = path
                    .strip_prefix(&root)
                    .expect("under src")
                    .display()
                    .to_string();
                let text = std::fs::read_to_string(&path).expect("source file");
                routed.insert(
                    relative,
                    (
                        text.matches("Prng::new(").count(),
                        text.matches("Prng::lcg(").count(),
                        text.matches("Prng::sfc(").count(),
                    ),
                );
            }
        }
        // Implementation files only: unit tests may sample from any family.
        let implementation: Vec<_> = routed
            .iter()
            .filter(|(name, _)| !name.contains("/tests") && !name.starts_with("vm/custom/tests"))
            .map(|(name, counts)| (name.as_str(), *counts))
            .collect();
        for (name, (plain, _lcg, sfc)) in &implementation {
            match *name {
                // Transport, cipher material and noise spelling ride sfc64.
                "vm/custom/transport.rs" | "vm/custom/chacha.rs" | "vm/custom/cipher.rs" => {
                    assert_eq!(*plain, 0, "{name} still samples from the shape stream");
                    assert!(*sfc > 0, "{name} never opens an sfc stream");
                }
                // Structure and per-handler mixing ride the full-period LCG.
                "vm/custom/lowering.rs" | "vm/custom/structure.rs" | "vm/custom/semantic.rs" => {
                    assert_eq!(*plain, 0, "{name} still samples from the shape stream");
                }
                _ => {}
            }
        }
        // No implementation file may sample a bounded value with a remainder any
        // more: `scale` is the only legal mapping, so a new domain cannot silently
        // reintroduce the bias this batch removed.
        let mut modulo = Vec::new();
        for (name, _) in &routed {
            if name.contains("/tests") || name.starts_with("vm/custom/tests") || name == "random.rs"
            {
                continue;
            }
            let text = std::fs::read_to_string(root.join(name)).expect("source file");
            for (line, content) in text.lines().enumerate() {
                if content.contains("next_u64() %") || content.contains("next_u64()%") {
                    modulo.push(format!("{name}:{}", line + 1));
                }
            }
        }
        assert!(
            modulo.is_empty(),
            "bounded draws must go through Prng::index (bias-free), found {modulo:?}"
        );

        // ...and the two families have to be live at all.
        let totals = routed
            .values()
            .fold((0, 0, 0), |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2));
        assert!(totals.1 >= 6, "only {} lcg streams", totals.1);
        assert!(totals.2 >= 6, "only {} sfc streams", totals.2);
        assert!(
            totals.0 >= 6,
            "output-shape domains lost their stream: {totals:?}"
        );
    }

    #[test]
    fn reject_equal_forms_are_exact_and_never_read_twice() {
        // Every form the sampler can return must reject exactly when the two
        // sides differ, over the whole read domain - including the
        // cursor-advancing `left` side, which the pure flag gates.
        for pure in [false, true] {
            let mut rng = Prng::lcg(0x6b31_5f72_656a_6563);
            let mut seen = std::collections::BTreeSet::new();
            for _ in 0..400 {
                let text = rng.reject_unequal("a", "b", pure);
                seen.insert(text.clone());
                for (left, right) in [
                    (0i64, 0i64),
                    (0, 1),
                    (1, 0),
                    (255, 255),
                    (255, 254),
                    (65536, 65535),
                    (-3, -3),
                    (-3, 3),
                ] {
                    let rejects = eval_rejects(&text, left, right);
                    assert_eq!(
                        rejects,
                        left != right,
                        "{text} at a={left} b={right}: expected {}",
                        if left != right { "reject" } else { "accept" }
                    );
                }
            }
            // The impure family has four members and the pure one five; a
            // collapsed helper would leave the census short of that.
            assert!(
                seen.len() >= if pure { 5 } else { 4 },
                "pure={pure} only produced {seen:?}"
            );
        }
    }

    /// Evaluate one `reject_unequal` form for `a = left`, `b = right`. Returns
    /// whether the guard *rejects* (true when the sides differ), and panics on
    /// anything the helper cannot emit so a new form cannot slip through uncovered.
    fn eval_rejects(text: &str, left: i64, right: i64) -> bool {
        let trimmed = text.trim();
        if let Some(inner) = trimmed
            .strip_prefix("not(")
            .and_then(|body| body.strip_suffix(')'))
        {
            // not(a==b)
            let (a, b) = split(inner, "==").expect("not(a==b)");
            return side(a, left, right) != side(b, left, right);
        }
        if let Some(diff) = trimmed.strip_suffix("~=0") {
            // a-b~=0 or b-a~=0
            let (a, b) = split(diff, "-").expect("difference form");
            return side(a, left, right) - side(b, left, right) != 0;
        }
        if let Some(rest) = trimmed.strip_suffix("<b or b<a") {
            // The order form is emitted with the sides in place of `a`/`b`, so the
            // suffix check above covers the shape; `rest` must end at the left side.
            let _ = rest;
        }
        if trimmed.contains(" or ") {
            let (first, second) = trimmed.split_once(" or ").expect("order form");
            let (a, b) = split(first, "<").expect("a<b");
            let (c, d) = split(second, "<").expect("b<a");
            assert_eq!(
                (a, b, c, d),
                ("a", "b", "b", "a"),
                "unexpected order form {trimmed}"
            );
            return left < right || right < left;
        }
        let (a, b) = split(trimmed, "~=").expect("plain a~=b");
        assert_eq!((a, b), ("a", "b"));
        left != right
    }

    fn split<'a>(text: &'a str, op: &str) -> Option<(&'a str, &'a str)> {
        text.trim().split_once(op)
    }

    fn side(token: &str, left: i64, right: i64) -> i64 {
        match token.trim() {
            "a" => left,
            "b" => right,
            other => panic!("unexpected side {other:?}"),
        }
    }
}
