use std::collections::{hash_map::RandomState, BTreeSet};
use std::fmt::Write;
use std::hash::{BuildHasher, Hasher};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;
use std::time::{SystemTime, UNIX_EPOCH};

/// Sampling families behind the one stream type the tool uses.
///
/// Every layout decision used to ride a single xorshift64* stream, which meant
/// one recovered draw sequence was one step from rolling the others: same mixer,
/// same state, same period. Each domain still owns its own seed-tagged stream,
/// and now the domains also own different *mixing families*, so no single
/// recurrence explains names, validator shape and transport layout at once:
///
/// * [`Family::Xs`] - xorshift64*: output shape (identifier pools, name
///   shortening, method/key maps).
/// * [`Family::Lcg`] - a 64-bit linear congruential generator with Hull-Dobell
///   full-period constants and a bijective output finalizer: structure (the
///   validator's search tree, the lane route, register/operand lowering, the
///   per-handler routine arms).
/// * [`Family::Sfc`] - an sfc64-style four-word mixing state: transport and
///   noise (alphabets, segment order, key material, spelling pools).
///
/// A family is a *sampling* choice only: nothing here is presented as a cipher,
/// and no generated byte depends on anything but (seed, family, call order).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum Family {
    Xs,
    Lcg,
    Sfc,
}

/// Multiplier and increment of [`Family::Lcg`]. They stay `pub(crate)` so the
/// gate can verify the Hull-Dobell conditions on the constants the generator
/// actually uses instead of on restated copies: with m = 2^64 the conditions are
/// "increment is odd" and "multiplier - 1 is a multiple of every prime factor of
/// m, and of 4 because 4 divides m". Since 2 is the only prime factor of 2^64,
/// those two facts give a period of exactly 2^64 from every start state.
pub(crate) const LCG_MULT: u64 = 0x0000_0369_3ea1_f41d;
pub(crate) const LCG_INCR: u64 = 0x1405_7b7e_f767_814f;

/// Small deterministic generator for layout and identifier randomization.
///
/// This is deliberately not presented as a cryptographic primitive. Data
/// encryption and key derivation belong to a later milestone.
pub(crate) struct Prng {
    family: Family,
    state: u64,
    /// Mixing words, used only by [`Family::Sfc`].
    aux: [u64; 3],
}

/// Bounded draw with no division and no remainder: one 128-bit product of the
/// sample and the bound, keeping the high half (multiply-shift). The bucket
/// decision rides the top bits of the sample, so a family's structurally weak
/// low bits - an LCG's bit 0 alternates, `x * odd` keeps a xorshift's bit 0 at
/// period 2 - never pick a bucket, and every bucket's preimage differs by at
/// most one value. `raw % upper` instead hands its whole surplus to the first
/// `2^64 mod upper` buckets, which is exactly the kind of predictable structure
/// an analyst looks for when guessing how many arms a table has.
pub(crate) fn scale(raw: u64, upper: usize) -> usize {
    if upper <= 1 {
        0
    } else {
        (((raw as u128) * (upper as u128)) >> 64) as usize
    }
}

/// Luau-only transient-buffer reconstruction widths. Entry transitions use a
/// shuffled permutation of all five, so one generated VM mixes the APIs rather
/// than merely making them probabilistically reachable across many seeds.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum BufferRead {
    U8,
    U16,
    U32,
    I32,
    F64,
}

impl Prng {
    pub fn new(seed: u64) -> Self {
        Self::with_family(Family::Xs, seed)
    }

    /// Full-period LCG stream, see [`Family::Lcg`] and [`LCG_MULT`]/[`LCG_INCR`].
    pub fn lcg(seed: u64) -> Self {
        Self::with_family(Family::Lcg, seed)
    }

    /// sfc64-style stream, see [`Family::Sfc`].
    pub fn sfc(seed: u64) -> Self {
        Self::with_family(Family::Sfc, seed)
    }

    /// Which mixer this stream uses. Test-only: no generated byte depends on
    /// it, but the family-split gates below read it.
    #[cfg(test)]
    pub fn family(&self) -> Family {
        self.family
    }

    fn with_family(family: Family, seed: u64) -> Self {
        let state = if seed == 0 {
            0x9e37_79b9_7f4a_7c15
        } else {
            seed
        };
        let mut random = Self {
            family,
            state,
            aux: [0; 3],
        };
        if family == Family::Sfc {
            // The four mixing words come from one seed via splitmix64, then the
            // mixer is warmed up so a caller never sees the seeding arithmetic.
            let mut source = state;
            let mut words = [0u64; 4];
            for word in words.iter_mut() {
                source = source.wrapping_add(0x9e37_79b9_7f4a_7c15);
                let mut value = source;
                value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
                value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
                *word = value ^ (value >> 31);
            }
            random.state = words[0];
            random.aux = [words[1], words[2], words[3]];
            // An all-zero mixing state would be a fixed point; the seeding cannot
            // produce one, and this keeps that true for any future seeder.
            if random.state | random.aux[0] | random.aux[1] | random.aux[2] == 0 {
                random.state = 0x9e37_79b9_7f4a_7c15;
            }
            for _ in 0..12 {
                random.next_u64();
            }
        }
        random
    }

    pub fn next_u64(&mut self) -> u64 {
        match self.family {
            Family::Xs => {
                let mut value = self.state;
                value ^= value >> 12;
                value ^= value << 25;
                value ^= value >> 27;
                self.state = value;
                value.wrapping_mul(0x2545_f491_4f6c_dd1d)
            }
            Family::Lcg => {
                // One full-period state step, then a bijective finalizer. The
                // finalizer cannot shorten the state period (it is a permutation
                // of the state) and it removes the LCG's low-bit regularity from
                // every consumer, including any that reads bit 0 directly.
                self.state = self.state.wrapping_mul(LCG_MULT).wrapping_add(LCG_INCR);
                let mut value = self.state;
                value = (value ^ (value >> 33)).wrapping_mul(0xff51_afd7_ed55_8ccd);
                value = (value ^ (value >> 33)).wrapping_mul(0xc4a9_fdd1_9460_9c73);
                value ^ (value >> 33)
            }
            Family::Sfc => {
                // Four words: two shift/xor mixing words, one additive mixing word
                // and a counter folded into the output. Carries make the output
                // depend on all three mixing words at once.
                let result = self
                    .state
                    .wrapping_add(self.aux[0])
                    .wrapping_add(self.aux[2]);
                self.aux[2] = self.aux[2].wrapping_add(1).wrapping_add(result);
                let mixed = self.state ^ self.aux[0];
                self.state = self.aux[0].wrapping_add(self.aux[0] << 5);
                self.aux[0] = (self.aux[1] >> 3) ^ mixed;
                self.aux[1] = mixed.wrapping_add(result);
                result
            }
        }
    }

    /// One unbiased coin. Rides the top bit of the draw for the same reason
    /// [`scale`] does.
    pub fn coin(&mut self) -> bool {
        (self.next_u64() >> 63) != 0
    }

    pub fn index(&mut self, upper: usize) -> usize {
        scale(self.next_u64(), upper)
    }

    pub fn shuffle<T>(&mut self, values: &mut [T]) {
        for index in (1..values.len()).rev() {
            let other = self.index(index + 1);
            values.swap(index, other);
        }
    }

    pub fn unique_opcodes(&mut self, count: usize) -> Vec<u16> {
        let mut used = BTreeSet::new();
        let mut result = Vec::with_capacity(count);
        while result.len() < count {
            // 257..=65256, drawn through the same bias-free bounded sampler as
            // every other choice in the tool.
            let candidate = 257 + self.index(65_000) as u16;
            if used.insert(candidate) {
                result.push(candidate);
            }
        }
        result
    }

    /// Spell an exact non-negative integer using only forms accepted by the
    /// selected output target. Lua 5.1 receives decimal/hexadecimal forms;
    /// Luau may additionally receive binary digits and separators.
    pub fn integer_literal(&mut self, value: u64, luau: bool) -> String {
        match self.index(if luau { 3 } else { 2 }) {
            0 => value.to_string(),
            1 => format!("0x{value:x}"),
            2 => {
                let digits = format!("{value:b}");
                let first = {
                    let remainder = digits.len() % 4;
                    if remainder == 0 {
                        4
                    } else {
                        remainder
                    }
                };
                let mut result = String::from("0b");
                result.push_str(&digits[..first]);
                for chunk in digits.as_bytes()[first..].chunks(4) {
                    result.push('_');
                    result.push_str(std::str::from_utf8(chunk).expect("binary digits are UTF-8"));
                }
                result
            }
            _ => unreachable!(),
        }
    }

    /// Emit one of several side-effect-free dispatcher comparisons. Only the
    /// opcode comparison changes; handler evaluation order stays unchanged.
    pub fn dispatch_condition(&mut self, opcode: u16, luau: bool) -> String {
        self.dispatch_condition_for("o", opcode, luau)
    }

    /// Variable-parameterized form used by the semantic recipe dispatcher.
    /// The caller supplies an internal identifier, never user source.
    pub fn dispatch_condition_for(&mut self, variable: &str, opcode: u16, luau: bool) -> String {
        let literal = self.integer_literal(u64::from(opcode), luau);
        self.dispatch_shape(variable, &literal)
    }

    /// Goal 6 (part 3): the same four dispatcher shapes over an *opaque* spelling
    /// of the opcode -- see [`Prng::opaque_literal`]. Every form is an exact
    /// arithmetic/compare context, so the reconstruction can drop in unchanged,
    /// and the four shapes are the same four the plain spelling uses.
    pub fn dispatch_condition_opaque(
        &mut self,
        variable: &str,
        opcode: u16,
        luau: bool,
        source: &str,
    ) -> String {
        let literal = self.opaque_literal(u64::from(opcode), luau, source);
        self.dispatch_shape(variable, &literal)
    }

    fn dispatch_shape(&mut self, variable: &str, literal: &str) -> String {
        debug_assert!(variable
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_'));
        let mut result = String::new();
        match self.index(4) {
            0 => write!(result, "{variable}=={literal}").unwrap(),
            1 => write!(result, "{literal}=={variable}").unwrap(),
            2 => write!(result, "not({variable}~={literal})").unwrap(),
            3 => write!(result, "{variable}-{literal}==0").unwrap(),
            _ => unreachable!(),
        }
        result
    }

    /// Spell a "this field must match that value" guard's *reject condition* in
    /// one of several exactly equivalent forms: every result is true exactly when
    /// the two sides differ, which is what the emitted `if <it> then E()end` uses.
    ///
    /// The validator wrote every header, watermark and known-answer rejection as
    /// `left ~= right`, which turned the whole load-time check block into a single
    /// grep anchor: one search found every guard and its pass/fail polarity. The
    /// forms below differ in shape only - same predicate, same short-circuit
    /// structure, same fail-closed behaviour - and which one a site gets is a
    /// per-seed choice like every other spelling in the tool.
    ///
    /// Each form evaluates both sides exactly once. The two-sided order test is
    /// offered only when `pure` says neither side can have an effect, because the
    /// header reads (`b8()`, `b32()`, the segment cursors) advance a read position:
    /// reading one byte twice would shift every field behind it and turn a
    /// validator into a corrupter.
    pub fn reject_unequal(&mut self, left: &str, right: &str, pure: bool) -> String {
        // Both sides must be atomic for the difference forms to stay exact under
        // Lua's left-associative `+`/`-`: a caller that needs a compound operand
        // parenthesizes it. Commas are allowed only inside the parentheses of a
        // call, which is a single evaluation.
        for side in [left, right] {
            debug_assert!(side
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || b"_.#(),".contains(&byte)));
        }
        let text = match self.index(if pure { 5 } else { 4 }) {
            0 => format!("{left}~={right}"),
            1 => format!("not({left}=={right})"),
            2 => format!("{left}-{right}~=0"),
            3 => format!("{right}-{left}~=0"),
            _ => format!("{left}<{right} or {right}<{left}"),
        };
        text
    }

    /// Side-effect-free boundary test for the validator's binary search tree:
    /// `variable < bound` (below) or its exact complement `variable >= bound`.
    /// Each rides in one of several spellings and every bound is byte-sized, so
    /// all forms stay exact on both targets (no double rounding is involved).
    pub fn boundary_condition(
        &mut self,
        variable: &str,
        bound: u16,
        below: bool,
        luau: bool,
    ) -> String {
        let literal = self.integer_literal(u64::from(bound), luau);
        self.boundary_shape(variable, &literal, below)
    }

    /// Goal 6 (part 3): a binary-search bound -- the number that says where a
    /// partition cuts -- spelled as an opaque reconstruction instead of a
    /// literal. Both polarities keep their exact-complement relationship: the
    /// reconstruction is one fixed value, only its spelling varies.
    pub fn boundary_condition_opaque(
        &mut self,
        variable: &str,
        bound: u16,
        below: bool,
        luau: bool,
        source: &str,
    ) -> String {
        let literal = self.opaque_literal(u64::from(bound), luau, source);
        self.boundary_shape(variable, &literal, below)
    }

    fn boundary_shape(&mut self, variable: &str, literal: &str, below: bool) -> String {
        debug_assert!(variable
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_'));
        let mut result = String::new();
        if below {
            match self.index(5) {
                0 => write!(result, "{variable}<{literal}"),
                1 => write!(result, "{literal}>{variable}"),
                2 => write!(result, "not({variable}>={literal})"),
                3 => write!(result, "{variable}-{literal}<0"),
                _ => write!(result, "{literal}-{variable}>0"),
            }
        } else {
            match self.index(4) {
                0 => write!(result, "{variable}>={literal}"),
                1 => write!(result, "{literal}<={variable}"),
                2 => write!(result, "not({variable}<{literal})"),
                _ => write!(result, "{variable}-{literal}>=0"),
            }
        }
        .unwrap();
        result
    }

    /// One numeric-interval test for the semantic interpreter's opcode dispatch:
    /// `variable <= bound` (`below`) or its exact complement `variable > bound`,
    /// so an interval partition can be walked with either polarity and both
    /// spellings cut the value domain in the same place.
    ///
    /// Three of the eight forms hide the dispatch variable behind the constant
    /// tautology `(v<=v and v or K)`, which is the identity for any number and
    /// therefore cannot change which interval a real dispatch value lands in.
    /// The point is that no raw `rid<=1234` survives as a grep anchor: a reader
    /// has to prove the guard is an identity before the bounds mean anything. If
    /// `v` were nil or false the guard yields `K`, a plain number, so such a
    /// value still reaches exactly one leaf - and every leaf keeps its own
    /// equality test and closes with `else E()end`, so an unforeseen value
    /// aborts instead of selecting a handler.
    pub fn interval_condition(
        &mut self,
        variable: &str,
        bound: u16,
        noise: u16,
        below: bool,
    ) -> String {
        // Both numbers are plain decimals by construction: a bound is not a
        // value the chain ever tests for equality, so its only job is to look
        // like every other three-to-five digit number in the shell, where hex
        // and grouped binary would cost 1-15 extra bytes apiece without hiding
        // anything (contrast `dispatch_condition`, whose literals *are* opcodes
        // and therefore gain from an unusual spelling).
        let literal = bound.to_string();
        self.interval_shape(variable, &literal, noise, below)
    }

    /// Goal 6 (part 3): the interval bound -- the partition boundary of the
    /// opcode dispatch chain -- as an opaque reconstruction. The tautology guard
    /// forms keep hiding the *variable*; the bound stops being a readable number
    /// in every form, so no `<= 1234` anchor survives and the partition cannot be
    /// read off the text without folding arithmetic on the runtime partition.
    pub fn interval_condition_opaque(
        &mut self,
        variable: &str,
        bound: u16,
        noise: u16,
        below: bool,
        luau: bool,
        source: &str,
    ) -> String {
        let literal = self.opaque_literal(u64::from(bound), luau, source);
        self.interval_shape(variable, &literal, noise, below)
    }

    fn interval_shape(&mut self, variable: &str, literal: &str, noise: u16, below: bool) -> String {
        debug_assert!(variable
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_'));
        let guard = format!("({variable}<={variable} and {variable} or {noise})");
        let mut result = String::new();
        if below {
            match self.index(8) {
                0 => write!(result, "{variable}<={literal}"),
                1 => write!(result, "{literal}>={variable}"),
                2 => write!(result, "not({variable}>{literal})"),
                3 => write!(result, "{variable}-{literal}<=0"),
                4 => write!(result, "{literal}-{variable}>=0"),
                5 => write!(result, "{guard}<={literal}"),
                6 => write!(result, "not({guard}>{literal})"),
                _ => write!(result, "{guard}-{literal}<=0"),
            }
        } else {
            match self.index(8) {
                0 => write!(result, "{variable}>{literal}"),
                1 => write!(result, "{literal}<{variable}"),
                2 => write!(result, "not({variable}<={literal})"),
                3 => write!(result, "{variable}-{literal}>0"),
                4 => write!(result, "{literal}-{variable}<0"),
                5 => write!(result, "{guard}>{literal}"),
                6 => write!(result, "not({guard}<={literal})"),
                _ => write!(result, "{guard}-{literal}>0"),
            }
        }
        .unwrap();
        result
    }

    /// Goal 6 (part 3): the opaque-constant toolbox.
    ///
    /// A *meaningful* constant -- a CFF state number, a binary-search bound, a
    /// ChaCha8 sigma word -- is the kind of number a reader greps for, because
    /// recognising `0x61707865` or a stable `w==567` names the construction.
    /// This spells such a value as **two algebraically exact reconstructions
    /// selected by an always-true guard over a runtime local**:
    ///
    /// ```text
    /// ((<source><=<source>)and(<a>+<b>)or(<value>+<k>-<k>))
    /// ```
    ///
    /// Three properties matter, and each is gated by a unit test below:
    ///
    /// * **No spelling of the value.** Every arm is built from operands that are
    ///   themselves different from `value`, so the number never appears as a
    ///   decimal (or, after the P1 respeller, hex/scientific) token. A reader has
    ///   to fold arithmetic to recover it.
    /// * **Two arms, not one.** Both arms are exact and the guard only chooses a
    ///   *spelling*; neither arm is a copy of the other. A reader cannot decide
    ///   which reconstruction a site uses without evaluating the guard, and the
    ///   guard reads a runtime value (a state variable, a ChaCha round argument)
    ///   that has no static value in the delivered text.
    /// * **Sound by construction.** Because both arms equal `value`, the guard
    ///   cannot change behaviour even when it is false -- NaN, a wrapped value, a
    ///   metatable, anything. There is no unreachable-arm assumption anywhere, so
    ///   the substitution is exact for every input, not merely for the inputs the
    ///   emitter expected.
    ///
    /// The operand pools skip the audit-nice literals ([`Prng::NICE_LITERALS`]),
    /// so the nice-constant census cannot move by drawing an operand that is
    /// itself an anchor. Small values are allowed but only the offset families
    /// apply to them (a split of `2` into two smaller operands does not exist),
    /// and every arm is dropped if its own text happens to spell the value --
    /// which is what keeps `(1*2)` from standing in for `2`.
    pub fn opaque_literal(&mut self, value: u64, luau: bool, source: &str) -> String {
        assert!(value < (1 << 31), "opaque_literal: {value} exceeds 2^31");
        assert!(
            !source.is_empty()
                && source
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || b"[]_.".contains(&byte)),
            "opaque_literal: {source:?} is not a simple runtime reference"
        );
        let mut arms: Vec<String> = Vec::new();
        // (a) additive split: two operands strictly below the value.
        if value >= 4 {
            let a = 1 + self.index((value - 1) as usize) as u64;
            let b = value - a;
            if !Self::audit_nice(a) && !Self::audit_nice(b) {
                arms.push(format!("({a}+{b})"));
            }
        }
        // (b) offset differences: the value plus a small offset, minus that
        // offset. Neither operand can be the value, so this family works for
        // every value including `0`; three independent draws guarantee two
        // distinct arms even when every other family is inapplicable.
        for _ in 0..3 {
            let k = 1 + self.index(199) as u64;
            if k != value && !Self::audit_nice(k) && !Self::audit_nice(value + k) {
                let arm = format!("({}-{k})", value + k);
                if !arms.contains(&arm) {
                    arms.push(arm);
                }
            }
        }
        // (c) doubling: exact for both parities (`2a-1` for odd values).
        {
            let b = value % 2;
            let a = (value + b) / 2;
            if !Self::audit_nice(a) && a != value {
                arms.push(if b == 0 {
                    format!("({a}*2)")
                } else {
                    format!("({a}*2-1)")
                });
            }
        }
        // (d) byte fold: the value spelled as its own big-endian bytes, the form
        // the anti-hook KAT words already used. Only for values that need a
        // second byte, i.e. where the fold is not a single digit plus zero.
        if value >= 256 {
            let bytes = value.to_be_bytes();
            let first = bytes
                .iter()
                .position(|&byte| byte != 0)
                .expect("nonzero value has a first byte");
            // Left-associative nesting, exactly like the emitted KAT spellings:
            // `((b0*256+b1)*256+b2)` -- a flat run would re-associate and change
            // the value under Lua's precedence rules.
            let mut text = Self::byte_token(bytes[first]);
            for &byte in &bytes[first + 1..] {
                let byte = Self::byte_token(byte);
                text = format!("({text}*256+{byte})");
            }
            arms.push(text);
        }
        // Every arm must also survive the *text* census, not just the operand
        // rule: the byte fold carries a literal `256` of its own, and any arm
        // that happens to spell the value while being built is dropped here
        // rather than shipped (for `256` that is exactly the byte-fold form).
        arms.retain(|arm| !Self::spells_value(value, arm));
        // (e) Luau only: a shift-shaped split. Native bitwise operators are not
        // in the language subset this tool parses (`src/parser.rs` has no `&`,
        // `|`, `~`, `<<`, `>>` at all -- only `//`), and the emitted text is
        // re-parsed by that same parser before it ships, so a "bit form" has to
        // be written in the operators the subset does have: the radix-`2^shift`
        // fold below is exactly the shift/mask arithmetic the emitted Luau bit
        // helpers perform, spelled inline. Both operands stay below the value,
        // so the digits of `value` never appear.
        if luau {
            let shift = 1 + self.index(7) as u32;
            let radix = 1u64 << shift;
            let high = value / radix;
            let low = value % radix;
            if high != 0
                && low != 0
                && high != value
                && low != value
                && !Self::audit_nice(high)
                && !Self::audit_nice(low)
            {
                arms.push(format!("({high}*2^{shift}+{low})"));
            }
        }
        arms.retain(|arm| !Self::spells_value(value, arm));
        // Normally the random offsets plus the other families already leave at
        // least two arms. If every candidate was filtered, finish the same
        // offset family deterministically without perturbing successful seeds.
        if arms.len() < 2 {
            for k in 1..=199u64 {
                if k != value && !Self::audit_nice(k) && !Self::audit_nice(value + k) {
                    let arm = format!("({}-{k})", value + k);
                    if !Self::spells_value(value, &arm) && !arms.contains(&arm) {
                        arms.push(arm);
                    }
                    if arms.len() >= 2 {
                        break;
                    }
                }
            }
        }
        assert!(
            arms.len() >= 2,
            "opaque_literal: value {value} has {} usable decompositions",
            arms.len()
        );
        let first = self.index(arms.len());
        let second = {
            let mut index = self.index(arms.len() - 1);
            if index >= first {
                index += 1;
            }
            index
        };
        let guard = self.opaque_guard(source, value, luau);
        let text = format!("({guard}and{}or{})", arms[first], arms[second]);
        debug_assert!(
            !Self::spells_value(value, &text),
            "opaque_literal: {text} still spells {value}"
        );
        text
    }

    /// Luau entry-transition reconstruction backed by two fresh, per-use
    /// buffers. The first buffer receives source/checkpoint-masked bytes in a
    /// seeded physical permutation; the second is normalized immediately before
    /// the selected typed read. Both are overwritten and released before return.
    ///
    /// This is deliberately inline rather than a common `decode(buffer, mode)`
    /// helper: each site has its own offsets, byte order, mask rotations and
    /// statement order. `ck` and `source` are sampled before and after the read,
    /// while every byte transform goes through captured bit32 functions. The
    /// other arm is the existing arithmetic reconstruction, so either guard
    /// result is exactly `value`.
    pub(crate) fn entry_buffer_literal(
        &mut self,
        value: u64,
        source: &str,
        read: BufferRead,
    ) -> String {
        assert!(value < (1 << 31), "entry_buffer_literal value out of range");
        let arithmetic = self.opaque_literal(value, true, source);
        let width = if read == BufferRead::F64 { 8 } else { 4 };
        let bytes: Vec<u8> = if read == BufferRead::F64 {
            (value as f64).to_bits().to_le_bytes().to_vec()
        } else {
            (value as u32).to_le_bytes().to_vec()
        };
        let input_offset = 1 + self.index(4);
        let output_offset = 1 + self.index(4);
        let mut physical: Vec<usize> = (0..width).collect();
        self.shuffle(&mut physical);
        let mut writes: Vec<usize> = (0..width).collect();
        let mut normalizes = writes.clone();
        let mut erases = writes.clone();
        self.shuffle(&mut writes);
        self.shuffle(&mut normalizes);
        self.shuffle(&mut erases);
        let rot_a = 1 + self.index(31);
        let rot_b = 1 + self.index(31);
        let mut slots: Vec<usize> = (40..100)
            .filter(|slot| *slot != 85 && *slot != 86)
            .collect();
        self.shuffle(&mut slots);
        slots.truncate(6);

        // Avoid reintroducing the value as an infrastructure/byte token when it
        // is itself small (notably 0, 1, 2, 85, 86 or 256).
        let token = |number: usize| {
            if number as u64 != value {
                return number.to_string();
            }
            let k = (1usize..16)
                .find(|k| {
                    *k as u64 != value
                        && (number + *k) as u64 != value
                        && !Self::audit_nice(*k as u64)
                        && !Self::audit_nice((number + *k) as u64)
                })
                .unwrap();
            format!("({}-{})", number + k, k)
        };
        let byte = |number: u8| {
            let number = usize::from(number);
            if number as u64 == value {
                let k = (1usize..16)
                    .find(|k| {
                        *k as u64 != value
                            && (number + *k) as u64 != value
                            && !Self::audit_nice(*k as u64)
                            && !Self::audit_nice((number + *k) as u64)
                    })
                    .unwrap();
                format!("({}-{})", number + k, k)
            } else {
                Self::byte_token(number as u8)
            }
        };

        let mut body = format!(
            "local g={{[{}]=BNE({}),[{}]=BNE({}),[{}]=BX(ck,{source})%4294967296}};g[4]=BA(BX(g[3],LR(g[3],{})),{});",
            slots[0],
            token(input_offset + width),
            slots[1],
            token(output_offset + width),
            slots[2],
            token(rot_a),
            token(255),
        );
        for logical in writes {
            write!(
                body,
                "BW8(g[1],{},BX({},g[4]));",
                token(input_offset + physical[logical]),
                byte(bytes[logical]),
            )
            .unwrap();
        }
        write!(body, "if BX(ck,{source})%4294967296~=g[3] then E()end;").unwrap();
        for logical in normalizes {
            write!(
                body,
                "BW8(g[2],{},BX(BR8(g[1],{}),g[4]));",
                token(output_offset + logical),
                token(input_offset + physical[logical]),
            )
            .unwrap();
        }
        let read_expr = match read {
            BufferRead::U8 => format!(
                "BO(BO(BR8(g[2],{a}),SHL(BR8(g[2],{b}),8)),BO(SHL(BR8(g[2],{c}),16),SHL(BR8(g[2],{d}),24)))",
                a = token(output_offset),
                b = token(output_offset + 1),
                c = token(output_offset + 2),
                d = token(output_offset + 3),
            ),
            BufferRead::U16 => format!(
                "BO(BR2(g[2],{}),SHL(BR2(g[2],{}),16))",
                token(output_offset),
                token(output_offset + 2),
            ),
            BufferRead::U32 => format!("BR3(g[2],{})", token(output_offset)),
            BufferRead::I32 => format!("BRI(g[2],{})", token(output_offset)),
            BufferRead::F64 => format!("BRF(g[2],{})", token(output_offset)),
        };
        write!(
            body,
            "g[6]={read_expr};g[5]=BA(BX(g[3],LR(g[3],{})),{});",
            token(rot_b),
            token(255)
        )
        .unwrap();
        for logical in erases {
            write!(
                body,
                "BW8(g[1],{},BX(g[5],{}));BW8(g[2],{},BX(g[5],{}));",
                token(input_offset + physical[logical]),
                token(logical),
                token(output_offset + logical),
                token(width - logical),
            )
            .unwrap();
        }
        write!(
            body,
            "g[1]=nil;g[2]=nil;if BX(ck,{source})%4294967296~=g[3] then E()end;return g[6]"
        )
        .unwrap();
        for (from, to) in (1..=6).zip(slots) {
            body = body.replace(&format!("g[{from}]"), &format!("g[{to}]"));
        }
        let buffer = format!("(function(){body};end)()");
        let guard = self.opaque_guard(source, value, true);
        // Entry states are validated integers, so this guard selects the
        // buffer arm in every normal run. The arithmetic arm remains an exact
        // fallback: soundness never depends on treating it as unreachable.
        let text = format!("({guard}and{buffer}or{arithmetic})");
        debug_assert!(
            value < 10 || !Self::spells_value(value, &text),
            "buffer form spells {value}: {text}"
        );
        text
    }

    /// Audit-nice literals (the structure layer's `nice_label` filter, kept as
    /// data here because this module sits below it in the dependency order).
    pub(crate) const NICE_LITERALS: [u16; 4] = [86, 256, 7225, 7396];

    /// The *complete* audit set (`product_audit` check1 / `transport::NICE_FULL`):
    /// every value the static audit counts as an anchor. The label filter above
    /// is the subset that fits the label domains; an operand pool has to reject
    /// all of them, because a spelled `85`, `86` or `65535` is exactly the grep
    /// handle the layer exists to remove.
    pub(crate) const AUDIT_NICE: [u64; 17] = [
        85, 7225, 614125, 52200625, 86, 7396, 636056, 54700816, 256, 65535, 65536, 16777216,
        2147483648, 2147483647, 4294967295, 4294967296, 4294967297,
    ];

    fn audit_nice(value: u64) -> bool {
        Self::AUDIT_NICE.contains(&value)
    }

    /// One byte of the byte-fold family, spelled so that a byte which is itself
    /// an audit anchor is never a token of its own: `85` becomes `(84+1)` and
    /// `86` becomes `(87-1)`, both exact and both made of non-anchor operands.
    /// Any other byte keeps its plain spelling.
    pub(crate) fn byte_token(byte: u8) -> String {
        let value = u64::from(byte);
        if !Self::audit_nice(value) {
            return value.to_string();
        }
        if !Self::audit_nice(value - 1) {
            format!("({}+1)", value - 1)
        } else {
            format!("({}-1)", value + 1)
        }
    }

    /// True when `text` contains `value` as a complete digit token -- the
    /// census rule every audit in this repository uses, so "hidden" here means
    /// hidden for the same reader.
    pub(crate) fn spells_value(value: u64, text: &str) -> bool {
        let needle = value.to_string();
        let bytes = text.as_bytes();
        text.match_indices(needle.as_str()).any(|(at, _)| {
            let before = at == 0 || !bytes[at - 1].is_ascii_digit();
            let end = at + needle.len();
            let after = end >= bytes.len() || !bytes[end].is_ascii_digit();
            before && after
        })
    }

    /// An always-true guard over a runtime reference, in the same families the
    /// structure layer already uses for its opaque pairs. Every form returns a
    /// boolean (or, for the `*0` form, a comparison) and reads `source` only, so
    /// inserting one cannot add an effect, a local or a read position. The Luau
    /// bit forms are offered only where `source` is an integer by construction.
    fn opaque_guard(&mut self, source: &str, value: u64, luau: bool) -> String {
        // The first three spell no digit at all, which is what lets `0` and `1`
        // be hidden too: every other form would put a `0`/`1` into the text.
        // `(x<=x)` and the reflexive `==`/`*` forms are not identities for NaN
        // or infinity, and they do not have to be: both arms of the surrounding
        // selection are the same value, so the guard can only choose a spelling.
        let mut forms = vec![
            format!("({source}<={source})"),
            format!("(not({source}<{source}))"),
            format!("({source}-{source}=={source}-{source})"),
            format!("({source}-{source}==0)"),
            format!("({source}~={source}-1)"),
            format!("({source}*0==0)"),
        ];
        if luau {
            // `//` is the one Luau-only operator this tool's parser accepts, and
            // it is an identity for integers, so it makes a Luau-shaped guard
            // that still parses (and that Lua 5.1 would reject, which is why it
            // is offered only for Luau).
            forms.push(format!("(({source}//1)=={source})"));
            forms.push(format!("({source}%2=={source}%2)"));
        }
        forms.retain(|form| !Self::spells_value(value, form));
        assert!(
            !forms.is_empty(),
            "opaque_guard: no digit-free form left for {value}"
        );
        forms[self.index(forms.len())].clone()
    }
}

/// Fresh per-generation default, not a cryptographic key. A process-random
/// std hasher initializes the stream once; a bijective mixer of the atomic
/// counter avoids repeats within a process (until the u64 counter wraps).
/// Explicit user seeds never pass through this nondeterministic path.
pub(crate) fn fresh_seed() -> u64 {
    static BASE: OnceLock<u64> = OnceLock::new();
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let base = *BASE.get_or_init(|| {
        let mut hasher = RandomState::new().build_hasher();
        hasher.write_u32(std::process::id());
        hasher.write(
            &SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos()
                .to_le_bytes(),
        );
        hasher.finish()
    });
    let mut value = base.wrapping_add(COUNTER.fetch_add(1, Ordering::Relaxed));
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}

#[cfg(test)]
mod tests {
    use super::{fresh_seed, scale, BufferRead, Family, Prng, LCG_INCR, LCG_MULT};

    #[test]
    fn default_seeds_are_distinct_across_threads() {
        let threads: Vec<_> = (0..8)
            .map(|_| std::thread::spawn(|| (0..128).map(|_| fresh_seed()).collect::<Vec<_>>()))
            .collect();
        let seeds: std::collections::BTreeSet<_> = threads
            .into_iter()
            .flat_map(|thread| thread.join().unwrap())
            .collect();
        assert_eq!(seeds.len(), 1024);
    }

    /// Which of the nine `boundary_condition` spellings a text uses. Kept as a
    /// separate classifier so the coverage assertion cannot be satisfied by a
    /// collapsed subset.
    fn boundary_label(text: &str) -> &'static str {
        let trimmed = text.trim();
        if let Some(inner) = trimmed
            .strip_prefix("not(")
            .and_then(|body| body.strip_suffix(')'))
        {
            return if inner.contains(">=") {
                "not>="
            } else {
                "not<"
            };
        }
        if let Some(rest) = trimmed.strip_prefix("o-") {
            return if rest.ends_with("<0") {
                "o-K<0"
            } else {
                "o-K>=0"
            };
        }
        if trimmed.starts_with("o<") {
            "o<"
        } else if trimmed.starts_with("o>=") {
            "o>="
        } else if trimmed.ends_with(">o") {
            "K>o"
        } else if trimmed.ends_with("<=o") {
            "K<=o"
        } else if trimmed.ends_with(">0") {
            "K-o>0"
        } else {
            panic!("unexpected boundary spelling {trimmed:?}")
        }
    }

    /// `boundary_condition` is what the validator's search tree partitions on,
    /// so every spelling it can emit must be an exact `<` / `>=` complement over
    /// the whole byte range: one wrong spelling would route records to the wrong
    /// arm (or past every arm) while still looking like a plain dispatch chain.
    /// The parser below accepts exactly the nine forms the renderer can produce
    /// and panics on anything else, so new spellings cannot go uncovered.
    #[test]
    fn boundary_conditions_partition_the_byte_range_exactly() {
        fn literal(token: &str) -> i64 {
            if let Some(hex) = token.strip_prefix("0x") {
                i64::from_str_radix(hex, 16).expect("hex literal")
            } else if let Some(bits) = token.strip_prefix("0b") {
                i64::from_str_radix(&bits.replace('_', ""), 2).expect("binary literal")
            } else {
                token.parse::<i64>().expect("decimal literal")
            }
        }
        fn side(token: &str, value: i64) -> i64 {
            let token = token.trim();
            if token == "o" {
                return value;
            }
            if let Some(rest) = token.strip_prefix("o-") {
                return value - literal(rest.trim());
            }
            if let Some(pos) = token.find("-o") {
                return literal(&token[..pos]) - value;
            }
            literal(token)
        }
        fn holds(text: &str, value: i64) -> bool {
            let trimmed = text.trim();
            if let Some(inner) = trimmed
                .strip_prefix("not(")
                .and_then(|body| body.strip_suffix(')'))
            {
                return !holds(inner, value);
            }
            // `<` and `>` are checked after their inclusive siblings so a
            // leading `<=` is never split into `<` plus a stray `=`.
            for op in ["<=", ">=", "<", ">"] {
                if let Some((left, right)) = trimmed.split_once(op) {
                    let (a, b) = (side(left, value), side(right, value));
                    return match op {
                        "<=" => a <= b,
                        ">=" => a >= b,
                        "<" => a < b,
                        _ => a > b,
                    };
                }
            }
            panic!("unparsable boundary condition {trimmed:?}");
        }

        for luau in [false, true] {
            let mut rng = Prng::new(0xb01d_2024);
            let mut seen = std::collections::BTreeSet::new();
            for bound in 0..=255u16 {
                for below in [true, false] {
                    let text = rng.boundary_condition("o", bound, below, luau);
                    // The bound in the text must be the requested one, and the
                    // two families must be exact complements at every value.
                    for value in [0i64, 1, 63, 64, 127, 128, 254, 255, 256] {
                        let below_holds = holds(&text, value)
                            == (if below {
                                value < i64::from(bound)
                            } else {
                                value >= i64::from(bound)
                            });
                        assert!(below_holds, "{text} at o={value} against {bound}");
                    }
                    seen.insert(boundary_label(&text));
                }
            }
            // Every spelling the renderer owns must actually show up, otherwise
            // the partition check above quietly covers a subset.
            assert_eq!(
                seen.len(),
                9,
                "{target} boundary spellings: {seen:?}",
                target = if luau { "luau" } else { "lua51" }
            );
        }
    }

    #[test]
    fn deterministic_and_unique() {
        let left = Prng::new(42).unique_opcodes(128);
        let right = Prng::new(42).unique_opcodes(128);
        assert_eq!(left, right);
        let mut sorted = left.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 128);
    }

    #[test]
    fn numeric_spelling_is_target_aware() {
        let mut lua = Prng::new(7);
        for _ in 0..64 {
            let literal = lua.integer_literal(0x1234, false);
            assert!(!literal.starts_with("0b"));
            assert!(!literal.contains('_'));
        }

        let mut luau = Prng::new(7);
        let literals: Vec<_> = (0..64)
            .map(|_| luau.integer_literal(0x1234, true))
            .collect();
        assert!(literals.iter().any(|literal| literal.starts_with("0b")));
        assert!(literals.iter().any(|literal| literal.contains('_')));

        let mut dispatch = Prng::new(19);
        for opcode in 1..=64 {
            let condition = dispatch.dispatch_condition_for("rid", opcode, true);
            assert!(condition.contains("rid"));
            let without_keywords = condition.replace("not", "").replace("rid", "");
            assert!(!without_keywords.contains('o'));
        }
    }

    #[test]
    fn lcg_meets_hull_dobell_and_walks_the_whole_reduced_state_space() {
        // Hull-Dobell for m = 2^64, read off the constants the generator uses:
        // the increment is odd, and multiplier - 1 is a multiple of 2 (the only
        // prime factor of m) and of 4 (because 4 divides m). Together these say
        // the state sequence has full period 2^64 from every start state.
        assert_eq!(LCG_INCR % 2, 1, "increment must be coprime with 2^64");
        assert_eq!(
            (LCG_MULT - 1) % 2,
            0,
            "multiplier - 1 must hit every prime factor of m"
        );
        assert_eq!(
            (LCG_MULT - 1) % 4,
            0,
            "m is a multiple of 4, so this is required too"
        );

        // The 2^64 walk itself cannot be run, so the same three conditions are
        // re-checked on a truncated modulus where the full cycle is enumerable:
        // a period-1 state cycle would show up here immediately.
        const M: u64 = 1 << 20;
        let mult = LCG_MULT % M;
        let incr = LCG_INCR % M;
        assert_eq!(incr % 2, 1);
        assert_eq!((mult - 1) % 4, 0);
        let mut seen = vec![false; M as usize];
        let mut state = 0x1234_5678_u64 % M;
        let start = state;
        for step in 0..M {
            state = (state.wrapping_mul(mult).wrapping_add(incr)) % M;
            assert!(!seen[state as usize], "state repeated after {step} steps");
            seen[state as usize] = true;
        }
        assert_eq!(state, start, "the reduced cycle must close exactly at m");
    }

    #[test]
    fn bounded_draw_reads_high_bits_and_spreads_preimages_evenly() {
        // Top-bit semantics: bucket 1 of two starts exactly at 2^63, whereas a
        // remainder mapping would decide this sample from its low bits instead.
        assert_eq!(scale(1 << 63, 2), 1);
        assert_eq!(scale((1 << 63) - 1, 2), 0);
        assert_ne!(
            scale(1 << 63, 3),
            ((1_u128 << 63) % 3) as usize,
            "a remainder draw and a multiply-shift draw must not agree here"
        );
        for bound in 1..=4096usize {
            assert_eq!(scale(0, bound), 0, "zero maps into the first bucket");
            assert_eq!(scale(u64::MAX, bound), bound - 1, "the draw is onto");
            // Preimage sizes differ by at most one value: bucket i spans
            // [ceil(i * 2^64 / bound), ceil((i + 1) * 2^64 / bound)).
            // Bucket 0 is skipped: its lower boundary is zero, so there is
            // no value below it to attribute to a previous bucket.
            for bucket in 1..bound.min(8) {
                let span = 1_u128 << 64;
                let low = (span * bucket as u128 + bound as u128 - 1) / bound as u128;
                assert_eq!(
                    scale(low as u64, bound),
                    bucket,
                    "lower boundary of {bucket}"
                );
                assert_eq!(
                    scale(low as u64 - 1, bound),
                    bucket - 1,
                    "the value below a boundary belongs to the previous bucket"
                );
            }
        }
    }

    #[test]
    fn every_family_balances_the_bits_a_consumer_might_read() {
        // Fixed seeds, so the tolerated spread is not a flaky statistical claim:
        // it just has to prove the finalizers actually shuffle carries upward and
        // that no family leaves a bucket empty (an LCG without a finalizer sets
        // bit 0 to a strict alternation, which shows up here as 50/50 per bit but
        // a 64-bucket histogram of the raw state would not be flat).
        for seed in [1u64, 7001, 4242, u64::MAX] {
            for mut random in [Prng::new(seed), Prng::lcg(seed), Prng::sfc(seed)] {
                let mut counts = [0u32; 64];
                for _ in 0..65_536 {
                    // 65,536 draws over 64 buckets expect 1,024 each; +-15% is
                    // far outside what a broken finalizer would produce.
                    counts[(random.next_u64() & 63) as usize] += 1;
                }
                assert!(
                    counts.iter().all(|&count| (870..=1180).contains(&count)),
                    "{seed} {:?} low-6-bit histogram {counts:?}",
                    random.family()
                );
            }
        }

        // Why the finalizer exists: the raw state walk of the same constants has
        // bit 0 in exact alternation, so a consumer reading the state directly
        // would see a period-2 signal in its own low bit.
        let mut state = 7u64;
        for step in 0..64 {
            state = state.wrapping_mul(LCG_MULT).wrapping_add(LCG_INCR);
            assert_eq!(
                state & 1,
                step % 2,
                "the un-finalized LCG state is expected to alternate in bit 0"
            );
        }
    }

    #[test]
    fn families_are_independent_streams_per_seed() {
        // The constructors really do select different mixers, not just different
        // starting states of one mixer.
        assert_eq!(Prng::new(1).family(), Family::Xs);
        assert_eq!(Prng::lcg(1).family(), Family::Lcg);
        assert_eq!(Prng::sfc(1).family(), Family::Sfc);
        for seed in [0u64, 1, 4095, 7001, 7351, 65535, u64::MAX] {
            let xs: Vec<_> = (0..32)
                .scan(Prng::new(seed), |r, _| Some(r.next_u64()))
                .collect();
            let lcg: Vec<_> = (0..32)
                .scan(Prng::lcg(seed), |r, _| Some(r.next_u64()))
                .collect();
            let sfc: Vec<_> = (0..32)
                .scan(Prng::sfc(seed), |r, _| Some(r.next_u64()))
                .collect();
            assert!(
                xs.iter().zip(lcg.iter()).all(|(a, b)| a != b),
                "{seed}: xs == lcg"
            );
            assert!(
                xs.iter().zip(sfc.iter()).all(|(a, b)| a != b),
                "{seed}: xs == sfc"
            );
            assert!(
                lcg.iter().zip(sfc.iter()).all(|(a, b)| a != b),
                "{seed}: lcg == sfc"
            );
            // Each family must be a function of its seed, not of anything else.
            assert_eq!(
                lcg,
                (0..32)
                    .scan(Prng::lcg(seed), |r, _| Some(r.next_u64()))
                    .collect::<Vec<_>>()
            );
            assert_ne!(
                lcg,
                (0..32)
                    .scan(Prng::lcg(seed ^ 1), |r, _| Some(r.next_u64()))
                    .collect::<Vec<_>>()
            );
        }
    }

    #[test]
    fn routed_domains_never_share_the_shape_stream() {
        // Structural guard for the split: the transport/crypto and structure
        // modules must not sample from the default (output-shape) family again,
        // and the per-handler structure domains must not fall back to xorshift.
        // Read from source, because the family is chosen per construction site.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut routed: std::collections::BTreeMap<String, (usize, usize, usize)> =
            std::collections::BTreeMap::new();
        let mut stack = vec![root.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).expect("source tree") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    stack.push(path);
                    continue;
                }
                if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                    continue;
                }
                let relative = path
                    .strip_prefix(&root)
                    .expect("under src")
                    .display()
                    .to_string();
                let text = std::fs::read_to_string(&path).expect("source file");
                routed.insert(
                    relative,
                    (
                        text.matches("Prng::new(").count(),
                        text.matches("Prng::lcg(").count(),
                        text.matches("Prng::sfc(").count(),
                    ),
                );
            }
        }
        // Implementation files only: unit tests may sample from any family.
        let implementation: Vec<_> = routed
            .iter()
            .filter(|(name, _)| !name.contains("/tests") && !name.starts_with("vm/custom/tests"))
            .map(|(name, counts)| (name.as_str(), *counts))
            .collect();
        for (name, (plain, _lcg, sfc)) in &implementation {
            match *name {
                // Transport, cipher material and noise spelling ride sfc64.
                "vm/custom/transport.rs" | "vm/custom/chacha.rs" | "vm/custom/cipher.rs" => {
                    assert_eq!(*plain, 0, "{name} still samples from the shape stream");
                    assert!(*sfc > 0, "{name} never opens an sfc stream");
                }
                // Structure and per-handler mixing ride the full-period LCG.
                "vm/custom/lowering.rs" | "vm/custom/structure.rs" | "vm/custom/semantic.rs" => {
                    assert_eq!(*plain, 0, "{name} still samples from the shape stream");
                }
                _ => {}
            }
        }
        // No implementation file may sample a bounded value with a remainder any
        // more: `scale` is the only legal mapping, so a new domain cannot silently
        // reintroduce the bias this batch removed.
        let mut modulo = Vec::new();
        for (name, _) in &routed {
            if name.contains("/tests") || name.starts_with("vm/custom/tests") || name == "random.rs"
            {
                continue;
            }
            let text = std::fs::read_to_string(root.join(name)).expect("source file");
            for (line, content) in text.lines().enumerate() {
                if content.contains("next_u64() %") || content.contains("next_u64()%") {
                    modulo.push(format!("{name}:{}", line + 1));
                }
            }
        }
        assert!(
            modulo.is_empty(),
            "bounded draws must go through Prng::index (bias-free), found {modulo:?}"
        );

        // ...and the two families have to be live at all.
        let totals = routed
            .values()
            .fold((0, 0, 0), |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2));
        assert!(totals.1 >= 6, "only {} lcg streams", totals.1);
        assert!(totals.2 >= 6, "only {} sfc streams", totals.2);
        assert!(
            totals.0 >= 6,
            "output-shape domains lost their stream: {totals:?}"
        );
    }

    #[test]
    fn reject_equal_forms_are_exact_and_never_read_twice() {
        // Every form the sampler can return must reject exactly when the two
        // sides differ, over the whole read domain - including the
        // cursor-advancing `left` side, which the pure flag gates.
        for pure in [false, true] {
            let mut rng = Prng::lcg(0x6b31_5f72_656a_6563);
            let mut seen = std::collections::BTreeSet::new();
            for _ in 0..400 {
                let text = rng.reject_unequal("a", "b", pure);
                seen.insert(text.clone());
                for (left, right) in [
                    (0i64, 0i64),
                    (0, 1),
                    (1, 0),
                    (255, 255),
                    (255, 254),
                    (65536, 65535),
                    (-3, -3),
                    (-3, 3),
                ] {
                    let rejects = eval_rejects(&text, left, right);
                    assert_eq!(
                        rejects,
                        left != right,
                        "{text} at a={left} b={right}: expected {}",
                        if left != right { "reject" } else { "accept" }
                    );
                }
            }
            // The impure family has four members and the pure one five; a
            // collapsed helper would leave the census short of that.
            assert!(
                seen.len() >= if pure { 5 } else { 4 },
                "pure={pure} only produced {seen:?}"
            );
        }
    }

    /// Evaluate one `reject_unequal` form for `a = left`, `b = right`. Returns
    /// whether the guard *rejects* (true when the sides differ), and panics on
    /// anything the helper cannot emit so a new form cannot slip through uncovered.
    fn eval_rejects(text: &str, left: i64, right: i64) -> bool {
        let trimmed = text.trim();
        if let Some(inner) = trimmed
            .strip_prefix("not(")
            .and_then(|body| body.strip_suffix(')'))
        {
            // not(a==b)
            let (a, b) = split(inner, "==").expect("not(a==b)");
            return side(a, left, right) != side(b, left, right);
        }
        if let Some(diff) = trimmed.strip_suffix("~=0") {
            // a-b~=0 or b-a~=0
            let (a, b) = split(diff, "-").expect("difference form");
            return side(a, left, right) - side(b, left, right) != 0;
        }
        if let Some(rest) = trimmed.strip_suffix("<b or b<a") {
            // The order form is emitted with the sides in place of `a`/`b`, so the
            // suffix check above covers the shape; `rest` must end at the left side.
            let _ = rest;
        }
        if trimmed.contains(" or ") {
            let (first, second) = trimmed.split_once(" or ").expect("order form");
            let (a, b) = split(first, "<").expect("a<b");
            let (c, d) = split(second, "<").expect("b<a");
            assert_eq!(
                (a, b, c, d),
                ("a", "b", "b", "a"),
                "unexpected order form {trimmed}"
            );
            return left < right || right < left;
        }
        let (a, b) = split(trimmed, "~=").expect("plain a~=b");
        assert_eq!((a, b), ("a", "b"));
        left != right
    }

    fn split<'a>(text: &'a str, op: &str) -> Option<(&'a str, &'a str)> {
        text.trim().split_once(op)
    }

    fn side(token: &str, left: i64, right: i64) -> i64 {
        match token.trim() {
            "a" => left,
            "b" => right,
            other => panic!("unexpected side {other:?}"),
        }
    }

    // --- Goal 6 (part 3): the opaque-constant toolbox ---------------------

    /// One value in the restricted grammar `opaque_literal` emits. Booleans and
    /// numbers are kept apart because Lua's `and`/`or` *return their operands*,
    /// which is exactly what makes `(guard and A or B)` an operator-free
    /// selection when A and B are numbers.
    #[derive(Clone, Copy, Debug, PartialEq)]
    enum OvValue {
        Num(i64),
        Bool(bool),
    }

    impl OvValue {
        fn truthy(self) -> bool {
            match self {
                OvValue::Bool(value) => value,
                OvValue::Num(_) => true,
            }
        }

        fn num(self) -> i64 {
            match self {
                OvValue::Num(value) => value,
                OvValue::Bool(value) => panic!("expected a number, got boolean {value}"),
            }
        }
    }

    /// A hand-written evaluator for the grammar the toolbox may emit: decimal
    /// integers, the one runtime reference `X`, `+ - *`, `< <= == ~=`, `and or
    /// not`, the Luau bit operators `& | ~`, and parentheses. It implements Lua
    /// precedence (`or` < `and` < comparison < additive < multiplicative <
    /// unary) so a mis-parenthesized reconstruction cannot pass.
    struct OvParser<'a> {
        bytes: &'a [u8],
        at: usize,
        source_value: i64,
    }

    impl<'a> OvParser<'a> {
        fn new(text: &'a str, source_value: i64) -> Self {
            OvParser {
                bytes: text.as_bytes(),
                at: 0,
                source_value,
            }
        }

        fn parse(text: &str, source_value: i64) -> i64 {
            OvParser::evaluate(text, source_value).num()
        }

        /// Same parse, keeping the value kind: the guards are booleans, and
        /// Lua's truthiness (only `false` is falsy) is what the caller checks.
        fn truthy(text: &str, source_value: i64) -> bool {
            OvParser::evaluate(text, source_value).truthy()
        }

        fn evaluate(text: &str, source_value: i64) -> OvValue {
            let mut parser = OvParser::new(text, source_value);
            let value = parser.or_expr();
            assert_eq!(parser.at, parser.bytes.len(), "trailing text in {text}");
            value
        }

        fn peek(&self) -> Option<u8> {
            self.bytes.get(self.at).copied()
        }

        fn eat(&mut self, text: &str) -> bool {
            if self.bytes[self.at..].starts_with(text.as_bytes()) {
                self.at += text.len();
                true
            } else {
                false
            }
        }

        fn or_expr(&mut self) -> OvValue {
            let mut left = self.and_expr();
            while self.eat("or") {
                let right = self.and_expr();
                left = if left.truthy() { left } else { right };
            }
            left
        }

        fn and_expr(&mut self) -> OvValue {
            let mut left = self.compare_expr();
            while self.eat("and") {
                let right = self.compare_expr();
                left = if left.truthy() { right } else { left };
            }
            left
        }

        fn compare_expr(&mut self) -> OvValue {
            let left = self.sum_expr();
            if self.eat("<=") {
                return OvValue::Bool(left.num() <= self.sum_expr().num());
            }
            if self.eat("==") {
                return OvValue::Bool(left.num() == self.sum_expr().num());
            }
            if self.eat("~=") {
                return OvValue::Bool(left.num() != self.sum_expr().num());
            }
            if self.eat("<") {
                return OvValue::Bool(left.num() < self.sum_expr().num());
            }
            left
        }

        /// A boolean operand is *not* an error at this level: Lua lets
        /// `(a<b) and x or y` ride through the operator levels, and only an
        /// arithmetic operator applied to a boolean would fail. The kind is
        /// therefore kept until an operator actually demands a number.
        fn sum_expr(&mut self) -> OvValue {
            let mut value = self.product_expr();
            loop {
                if self.eat("+") {
                    value = OvValue::Num(value.num() + self.product_expr().num());
                } else if self.eat("-") {
                    value = OvValue::Num(value.num() - self.product_expr().num());
                } else {
                    return value;
                }
            }
        }

        fn product_expr(&mut self) -> OvValue {
            let mut value = self.power_expr();
            loop {
                if self.eat("*") {
                    value = OvValue::Num(value.num() * self.power_expr().num());
                } else if self.eat("//") {
                    let divisor = self.power_expr().num();
                    assert!(divisor != 0, "floor division by zero");
                    value = OvValue::Num(value.num().div_euclid(divisor));
                } else if self.eat("/") {
                    value = OvValue::Num(value.num() / self.power_expr().num());
                } else if self.eat("%") {
                    let divisor = self.power_expr().num();
                    assert!(divisor != 0, "modulo by zero");
                    // Lua's `%` is the floored modulo, i.e. `rem_euclid` for a
                    // positive divisor -- the form every guard here uses.
                    value = OvValue::Num(value.num().rem_euclid(divisor));
                } else if self.eat("&") {
                    value = OvValue::Num(value.num() & self.power_expr().num());
                } else if self.eat("|") {
                    value = OvValue::Num(value.num() | self.power_expr().num());
                } else if self.bytes[self.at..].starts_with(b"~")
                    && !self.bytes[self.at..].starts_with(b"~=")
                {
                    self.at += 1;
                    value = OvValue::Num(value.num() ^ self.power_expr().num());
                } else {
                    return value;
                }
            }
        }

        /// `^` binds tighter than `*` and is right-associative in Lua, so it
        /// gets its own level (`2^3` in the Luau shift form must read as `8`,
        /// not as `(x*2)^3`).
        fn power_expr(&mut self) -> OvValue {
            let base = self.atom();
            if self.eat("^") {
                let exponent = self.power_expr().num();
                assert!(exponent >= 0, "negative exponent in a reconstruction");
                return OvValue::Num(base.num().pow(exponent as u32));
            }
            base
        }

        fn atom(&mut self) -> OvValue {
            if self.eat("(") {
                let value = self.or_expr();
                assert!(self.eat(")"), "unbalanced parentheses");
                return value;
            }
            if self.eat("not") {
                let value = self.atom();
                return OvValue::Bool(!value.truthy());
            }
            if self.eat("-") {
                return OvValue::Num(-self.atom().num());
            }
            if self.eat("X") {
                return OvValue::Num(self.source_value);
            }
            let start = self.at;
            while self.peek().is_some_and(|byte| byte.is_ascii_digit()) {
                self.at += 1;
            }
            assert!(self.at > start, "no atom at byte {start}");
            OvValue::Num(
                std::str::from_utf8(&self.bytes[start..self.at])
                    .unwrap()
                    .parse()
                    .unwrap(),
            )
        }
    }

    /// Split an emitted reconstruction into its (guard, arm, arm) parts. The
    /// guard forms and both arms are pure arithmetic/compare text with no
    /// `and`/`or` of their own, so the first two keywords are the separators and
    /// the assertion below is what keeps that true.
    fn opaque_parts<'a>(text: &'a str) -> (&'a str, &'a str, &'a str) {
        let body = text
            .strip_prefix('(')
            .and_then(|rest| rest.strip_suffix(')'))
            .expect("reconstruction is parenthesized");
        let (guard, rest) = body.split_once("and").expect("guard separator");
        let (first, second) = rest.split_once("or").expect("arm separator");
        (guard, first, second)
    }

    #[test]
    fn opaque_literals_hide_their_value_and_are_exact_under_both_arms() {
        let mut random = Prng::sfc(0x6f70_6171_7565_3631);
        let mut values: Vec<u64> = (100..1000).step_by(37).collect();
        values.extend([
            0, 1, 2, 3, 7, 8, 17, 86, 256, 512, 65_521, 65_535, 16_777_215,
        ]);
        values.extend([
            1_634_760_805,
            857_760_878,
            2_036_477_234,
            1_797_285_236,
            804_192_318,
            505_049_583,
            1_123_945_486,
        ]);
        for luau in [false, true] {
            for &value in &values {
                for _ in 0..8 {
                    let text = random.opaque_literal(value, luau, "X");
                    assert!(
                        !Prng::spells_value(value, &text),
                        "{text} still spells {value}"
                    );
                    assert!(
                        text.matches('(').count() == text.matches(')').count(),
                        "{text} has unbalanced parentheses"
                    );
                    let (guard, first, second) = opaque_parts(&text);
                    assert!(
                        !guard.contains("and") && !guard.contains("or"),
                        "guard {guard} is not atomic"
                    );
                    // Every guard outcome picks a spelling of the same value:
                    // that is the soundness argument, and it is checked here
                    // rather than argued.
                    assert_eq!(OvParser::parse(first, 5), value as i64, "arm {first}");
                    assert_eq!(OvParser::parse(second, 5), value as i64, "arm {second}");
                    assert!(OvParser::truthy(guard, 5), "guard {guard} must be true");
                    assert_eq!(OvParser::parse(&text, 5), value as i64, "whole {text}");
                    assert_eq!(OvParser::parse(&text, 0), value as i64, "whole {text} at 0");
                }
            }
        }
    }

    #[test]
    fn opaque_conditions_never_spell_their_bound() {
        let mut random = Prng::sfc(0x636f_6e64_6974_696f);
        for luau in [false, true] {
            for bound in [17u16, 86, 256, 512, 4096, 12_345, 65_535] {
                for _ in 0..8 {
                    let text = random.dispatch_condition_opaque("o", bound, luau, "o");
                    assert!(!Prng::spells_value(u64::from(bound), &text), "{text}");
                    let text = random.boundary_condition_opaque("o", bound, true, luau, "o");
                    assert!(!Prng::spells_value(u64::from(bound), &text), "{text}");
                    let text = random.boundary_condition_opaque("o", bound, false, luau, "o");
                    assert!(!Prng::spells_value(u64::from(bound), &text), "{text}");
                    let text = random.interval_condition_opaque("o", bound, 7, true, luau, "o");
                    assert!(!Prng::spells_value(u64::from(bound), &text), "{text}");
                    let text = random.interval_condition_opaque("o", bound, 7, false, luau, "o");
                    assert!(!Prng::spells_value(u64::from(bound), &text), "{text}");
                }
            }
        }
    }

    /// The strongest cheap check on the toolbox: every reconstruction is fed
    /// back through **the project's own parser** for the target it was built
    /// for. The emitted text is re-parsed before it ships (and again when it is
    /// shelled), so a form the parser rejects would be a latent generation
    /// failure no evaluation test could catch -- this is exactly how the native
    /// `~`/`|` xor forms were caught before shipping.
    #[test]
    fn opaque_forms_are_inside_the_tools_language_subset() {
        use crate::target::Target;
        let mut random = Prng::sfc(0x7375_6273_6574_6c75);
        for (target, luau) in [(Target::Lua51, false), (Target::Luau, true)] {
            for value in [0u64, 1, 2, 7, 17, 86, 100, 567, 4096, 65_535, 1_634_760_805] {
                for _ in 0..12 {
                    let text = random.opaque_literal(value, luau, "X");
                    let source = format!("local X=5\nlocal w={text}\nreturn w");
                    crate::parser::parse_source(&source, target).unwrap_or_else(|error| {
                        panic!("{target} parser rejected {text}: {error:?}")
                    });
                }
            }
        }
    }

    #[test]
    fn luau_buffer_reconstructions_are_inline_mixed_and_parseable() {
        use crate::target::Target;
        let reads = [
            BufferRead::U8,
            BufferRead::U16,
            BufferRead::U32,
            BufferRead::I32,
            BufferRead::F64,
        ];
        let signatures = ["BO(BO(BR8", "BR2(g[", "BR3(g[", "BRI(g[", "BRF(g["];
        for (index, read) in reads.into_iter().enumerate() {
            let value = 30_001 + index as u64 * 997;
            let mut random = Prng::lcg(0x6275_6666_6572_0000 ^ value);
            let text = random.entry_buffer_literal(value, "es", read);
            assert!(!Prng::spells_value(value, &text), "{text}");
            assert_eq!(text.matches("BNE(").count(), 2, "{text}");
            assert!(text.contains("BW8(") && text.contains(signatures[index]));
            assert!(text.matches("BX(ck,es)").count() >= 3, "{text}");
            assert!(!text.contains("BFS("), "fromstring is forbidden: {text}");
            assert_eq!(text.matches("=nil;").count(), 2, "{text}");
            let source = format!(
                "local BNE,BW8,BR8,BR2,BR3,BRI,BRF,BX,BA,BO,LR,SHL,E;local ck,es=9,7;es={text};return es"
            );
            crate::parser::parse_source(&source, Target::Luau)
                .unwrap_or_else(|error| panic!("{read:?}: {error:?}\n{text}"));
        }
        for value in 0..=4 {
            let mut random = Prng::lcg(0x736d_616c_6c00 + value);
            let text = random.entry_buffer_literal(value, "o", BufferRead::U16);
            assert!(text.contains("BNE(") && text.contains("=nil;"), "{text}");
        }
    }

    #[test]
    fn value_census_is_token_exact() {
        assert!(!Prng::spells_value(256, "2^8"));
        assert!(Prng::spells_value(256, "x==256"));
        assert!(!Prng::spells_value(256, "x==1256"));
        assert!(!Prng::spells_value(256, "x==2560"));
        assert!(!Prng::spells_value(86, "0x586"));
    }
}
